version: '3'

services:

  jenkins-master:
    image: "kastilochagin/priv:master"
    container_name: jenkins-master
    hostname: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - app-net

  jenkins-slave:
    image: "kastilochagin/priv:slave"
    container_name: jenkins-slave
    hostname: jenkins-slave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-net

volumes:
  jenkins-data:
    external: true

networks:
  app-net:
    external: true
